sudo: false

language: php

php:
  - 7.3

before_script:
  - composer selfupdate
  - composer install --prefer-dist

script:
  - vendor/bin/phpstan analyse -l max src/
  - vendor/bin/phpunit

cache:
  directories:
    - $HOME/.composer
