sudo: false

language: php

php:
  - 7.0
  - 7.1

before_script:
  - composer selfupdate
  - composer install --prefer-dist

script:
  - vendor/bin/phpunit

cache:
  directories:
    - $HOME/.composer
